packages:
  - name: daily-tasks
    functions:
      - name: reddit-sync
        runtime: nodejs:default
        limits:
          timeout: 60000  # 60 seconds
          memory: 256
        environment:
          APP_URL: ${APP_URL}
          SYNC_TOKEN: ${SYNC_TOKEN}
    # Schedule to run daily at 11:50 PM UTC (10 minutes before KB recrawl)
    # Cron format: minute hour day month weekday
    triggers:
      - name: daily-before-midnight
        type: SCHEDULED
        scheduledDetails:
          cron: "50 23 * * *"  # Every day at 11:50 PM UTC
          body:
            message: "Daily Reddit sync triggered"
